{% set name = "qpdf" %}
{% set version = "8.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qpdf/qpdf/archive/release-qpdf-{{version}}.tar.gz
  sha256: 71d9b6c77ac56521d86a481cb9e52c0774de106c1dcf7a0644a05bd1230be87e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2-autoconf  # [win]
    - m2-automake1.15  # [win]
    - automake  # [not win]
    - autoconf  # [not win]
    - m2-sed  # [win]
    - vs2015_win-64  # [win]
  host:
    - zlib
    - jpeg
    # this is because sha256sum is missing on osx:
    - coreutils  # [osx]
  run:
    - zlib
    - jpeg

test:
  commands:
    - qpdf --help

about:
  home: https://sourceforge.net/projects/qpdf/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Command-line program that does structural, content-preserving transformations on PDF files'
  description: |
    With QPDF, it is possible to copy objects from one PDF file into another and to manipulate the list of pages in a PDF file.
    This makes it possible to merge and split PDF files. The QPDF library also makes it possible for you to create PDF files from scratch.
    In this mode, you are responsible for supplying all the contents of the file, while the QPDF library takes care off all the syntactical representation of the objects, creation of cross references tables and, if you use them, object streams, encryption, linearization, and other syntactic details.
  doc_url: http://qpdf.sourceforge.net/files/qpdf-manual.html
  dev_url: https://github.com/qpdf/qpdf

extra:
  recipe-maintainers:
    - jenzopr
    - carlodri
