{% set name = "qpdf" %}
{% set version = "11.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qpdf/qpdf/releases/download/v{{ version }}/qpdf-{{ version }}.tar.gz
  sha256: defca435cf57d26f8a0619864841aa21f5469fddc6eb5662f62d8443021c069d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('qpdf') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - libjpeg-turbo
    - openssl
    - zlib

test:
  commands:
    - which qpdf     # [unix]
    - where qpdf     # [win]
    - qpdf --help    # [build_platform == target_platform]

about:
  home: https://qpdf.sourceforge.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: >-
    Command-line program that does structural, content-preserving transformations on PDF files
  description: |
    With QPDF, it is possible to copy objects from one PDF file into another
    and to manipulate the list of pages in a PDF file.  This makes it possible
    to merge and split PDF files. The QPDF library also makes it possible for
    you to create PDF files from scratch.  In this mode, you are responsible
    for supplying all the contents of the file, while the QPDF library takes
    care off all the syntactical representation of the objects, creation of
    cross references tables and, if you use them, object streams, encryption,
    linearization, and other syntactic details.
  doc_url: https://qpdf.readthedocs.io/
  dev_url: https://github.com/qpdf/qpdf

extra:
  recipe-maintainers:
    - jenzopr
    - carlodri
