{% set name = "qpdf" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qpdf/qpdf/archive/release-qpdf-{{version}}.tar.gz
  sha256: 1ec05520a285009f176a2db6c0ee608d3e0c2210466f047fef125659e5813593

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - autoconf
  host:
    - zlib
    - jpeg
  run:
    - zlib
    - jpeg

test:
  commands:
    - qpdf --help

about:
  home: https://sourceforge.net/projects/qpdf/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Command-line program that does structural, content-preserving transformations on PDF files'
  description: |
    With QPDF, it is possible to copy objects from one PDF file into another and to manipulate the list of pages in a PDF file.
    This makes it possible to merge and split PDF files. The QPDF library also makes it possible for you to create PDF files from scratch.
    In this mode, you are responsible for supplying all the contents of the file, while the QPDF library takes care off all the syntactical representation of the objects, creation of cross references tables and, if you use them, object streams, encryption, linearization, and other syntactic details.
  doc_url: http://qpdf.sourceforge.net/files/qpdf-manual.html
  dev_url: https://github.com/qpdf/qpdf

extra:
  recipe-maintainers:
    - jenzopr
